### ISSUE TITLE
Tab complete on screen -r

### ISSUE THREAD

**Issue by natiwhitney** [bfs/docker-cdh5-devbox#1]
To Whom It May Concern

(I think this is a catch-all repo for devbox-related issues?)

On devbox if I screen -r, I get a list of several screens that are attached. For example:
	15437.pts-3.64ea7176de27	(08/03/2016 10:03:19 PM)	(Detached)
	14463.pts-3.64ea7176de27	(08/03/2016 09:50:53 PM)	(Detached)
	14248.pts-0.64ea7176de27	(08/03/2016 09:46:52 PM)	(Attached)

However, if I type screen -r 144 and then <tab> it will not auto complete.

Idental operation tab completes on openstack.

Not the end of the world, but slightly annoying as I have to copy-paste the full name.

**Comment by ndigati** [comment]
@natiwhitney I fixed this by installing the bash_completion package in my devbox

```
sudo apt-get install bash-completion
```

**Comment by natiwhitney** [comment]
Hi Nick,

Great thank you!
